### ISSUE TITLE
Multiple stampie repositories

### ISSUE THREAD

**Issue by zspine** [stof/StampieExtra#2]
Hi!

There are 2 stampie repositories and not sure which one is more up to date.

https://github.com/Stampie/Stampie (last update:  as of today 22 days ago)
https://github.com/henrikbjorn/Stampie (last update:  Dec 14, 2014)

StampieExtra uses "henrikbjorn/stampie": "~0.10"

Thank you!

**Comment by stof** [comment]
The repo in the Stampie organization still has ``henrikbjorn/stampie`` as package name, as we have not yet renamed the package after moving it to the organization. So there is no issue.
